version: '3'
services:
        mysqlos:
                image: mysql:5.7
                volumes:
                        - mysql_storage_new:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: kumar
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: My_DB

        wpos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - mysqlos
                ports:
                        - 8080:80       
                environment:
                        WORDPRESS_DB_HOST: mysqlos:3306
                        WORDPRESS_DB_USER: kumar
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: My_DB
                volumes:
                        - wpos_storage_new:/var/www/html


volumes:
        wpos_storage_new:
	mysql_storage_new:
        mysql_storage_new:


